config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  #Lister les tâches (Read All)
  get "tasks", to: "tasks#index"

  #Créer une nouvelle tâche : Step 1: Get the form +  Step2 : Post
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  #Show une tâche (Read One)
  get "tasks/:id", to: "tasks#show", as: :task

  #Editer une tâche (Update)
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"

  #Supprimer une tâche (Delete)
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    # raise
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    # raise
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container justify-content-center bg-light">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1 class="text-center border-bottom bg-secondary py-3">My tasks</h1>
<ul class="list-unstyled">
  <% @tasks.each_with_index do |task, index| %>
    <li class="d-flex justify-content-between border-bottom">
      <%= link_to "#{index+1} | #{task.title} | Status : #{task.completed ? 'Completed' : 'Ongoing'}", task_path(task), class:"my-4" %>
      <%= link_to "Delete",
        task_path(task),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
        class:"m-3 btn btn-danger"
      %>
    </li>
  <% end %>
</ul>
<%= link_to "New task!", tasks_new_path, class:"btn btn-primary" %>

app/views/tasks/new.html.erb
<div class="d-flex align-items-center py-3">
  <%= form_with model: @task do |f| %>
    <div class="my-2">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="my-2">
      <%= f.label :details %>
      <%= f.text_field :details %>
    </div>
    <div class="my-2">
      <%= f.label :completed %>
      <%= f.check_box :completed %>
    </div>
    <%= f.submit %>
  <% end %>
</div>
<div>
  <%= link_to "Back", tasks_path, class:"btn btn-primary my-2" %>
</div>

app/views/tasks/show.html.erb
<h2 class="text-center py-3 border-bottom bg-secondary">Task: <%= @task.title.capitalize %></h2>
<div class="border-bottom">
  <p class="text-center">Description: <%= @task.details.capitalize %></p>
  <p class="text-center">Status: <%= @task.completed ? "Completed" : "Ongoing" %></p>
</div>

<div class="d-flex justify-content-center">
  <%= link_to "Edit", edit_path(@task), class:"btn btn-success m-3" %>
  <%= link_to "Back", tasks_path, class:"btn btn-primary m-3" %>
</div>